const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {d1,d2,d3}=require('./designs.js');
const PAGE=process.env.PAGE||path.join(__dirname,'..','studio.html');
const OUT=path.join(__dirname,'out'); fs.mkdirSync(OUT,{recursive:true}); fs.mkdirSync(path.join(OUT,'sample'),{recursive:true});
let state=[]; const blobs=new Map(); const log=[]; let MODE={canva:'image'};
const RESET='<style>:root{color-scheme:light;padding-top:env(safe-area-inset-top,0px);padding-bottom:env(safe-area-inset-bottom,0px)}body{margin:0;font:14px system-ui;background:#fafaf9}img{max-width:100%}[hidden]{display:none!important}</style>';
const body=req=>new Promise(r=>{const c=[];req.on('data',d=>c.push(d));req.on('end',()=>r(Buffer.concat(c)))});
function libCodes(p){const m={};for(const x of p.matchAll(/^(img-[0-9a-z]{8}) \| ([^|]+) \| "([^"]*)"/gm)) m[x[3]]=x[1];return m}
function respond(p){
  if(p.includes('You are the image analyst')){const out=[];for(const x of p.matchAll(/Image \d+ = (img-[0-9a-z]{8}) \| ([^|]+) \| "([^"]*)"/g)){const name=x[3],kind=x[2].trim();const style=/reference|briefing page/.test(kind)||/ref-|p\.\d/.test(name);out.push({code:x[1],what:`Test description of ${name}`,colours:['#2B1A12','#C8742E','#F3E6D3'],mood:'warm',focus:{x:0.7,y:0.5},textSpace:'bottom third',quality:'high',use:style?'style':'post',rights:style?'third-party':'client',notes:''})}return JSON.stringify(out)}
  if(p.includes('You are the Strategist')){const n=+(/exactly (\d+) items/.exec(p)||[0,3])[1];const fm=['portrait','portrait','story'];return JSON.stringify({summary:'Lançamento do primeiro café de origem única de Gurué para jovens profissionais em Maputo.',objective:'Notoriedade e visitas ao café em Outubro.',audiences:[{name:'Jovens profissionais em Maputo',insight:'Pagam por bom café mas assumem que o melhor é importado.'}],keyMessages:['Cultivado em Gurué a 1.200 m','Torrado em Maputo todas as terças'],tone:'Caloroso e orgulhoso, nunca pretensioso',mandatories:['Mencionar Gurué','@kulukacoffee'],restrictions:['Sem alegações de saúde'],visualMandatories:['Logo em todas as publicações','Laranja da embalagem #C8742E'],pillars:[{name:'Origem',purpose:'Orgulho no café moçambicano'},{name:'Torra',purpose:'Frescura'},{name:'Comunidade',purpose:'Trazer pessoas ao café'}],gaps:['Qual é o preço do pacote de 250 g?'],risks:['Promessas de frescura'],plan:Array.from({length:n},(_,i)=>({n:i+1,date:`2026-10-${12+i*4}`,platform:i%2?'Facebook':'Instagram',format:fm[i%3],pillar:['Origem','Torra','Comunidade'][i%3],angle:'...'}))})}
  if(p.includes('You are the Copywriter in a social media production pipeline')){const n=+(p.match(/"plan":\[(.*?)\]\}/s)?.[1].match(/"n":/g)||[1,1,1]).length;const P=[
    {pt:{kicker:'Origem única',headline:'Nascido em Gurué',subline:'Arábica de especialidade das colinas da Zambézia, torrado em Maputo.',body:'',cta:'',footnote:'',caption:'Cada chávena começa a 1.200 metros, nas colinas de Gurué.\n\nTorramos todas as terças-feiras em Maputo.',hashtags:['#KulukaCoffee','#Gurue','#FeitoEmMocambique'],altText:'Ramo de café com cerejas vermelhas e colinas verdes ao fundo.'},en:{kicker:'Single origin',headline:'Grown in Gurué',subline:'Specialty arabica from the hills of Zambézia, roasted in Maputo.',body:'',cta:'',footnote:'',caption:'Every cup starts 1,200 metres up in the hills of Gurué.\n\nWe roast every Tuesday in Maputo.',hashtags:['#KulukaCoffee','#Gurue','#MadeInMozambique'],altText:'Coffee branch with red cherries and green hills behind.'}},
    {pt:{kicker:'Torra da semana',headline:'Torrado à terça. Servido à quarta.',subline:'Pequenos lotes, torrados todas as terças-feiras em Maputo.',body:'',cta:'Prove a torra nova',footnote:'',caption:'Clara, média ou escura? Pergunte-nos o que muda na chávena.',hashtags:['#KulukaCoffee','#Maputo'],altText:'Chávena de café vista de cima.'},en:{kicker:"This week's roast",headline:'Roasted Tuesday. Poured Wednesday.',subline:'Small batches, roasted every Tuesday in Maputo.',body:'',cta:'Try the new roast',footnote:'',caption:'Light, medium or dark? Ask us what changes in the cup.',hashtags:['#KulukaCoffee','#Maputo'],altText:'Cup of coffee seen from above.'}},
    {pt:{kicker:'Sábado · 10h00',headline:'Sábados, com calma',subline:'',body:'Prova gratuita de três lotes de Gurué. Av. Julius Nyerere. 12 lugares.',cta:'Reserve por DM',footnote:'',caption:'Venha provar três lotes de Gurué lado a lado.',hashtags:['#KulukaCoffee','#MaputoFimDeSemana'],altText:'Três chávenas de café vistas de cima.'},en:{kicker:'Saturday · 10:00',headline:'Saturdays, slower',subline:'',body:'Free tasting of three Gurué lots. Av. Julius Nyerere. 12 seats.',cta:'Book via DM',footnote:'',caption:'Taste three Gurué lots side by side.',hashtags:['#KulukaCoffee','#MaputoWeekend'],altText:'Three cups of coffee seen from above.'}}];
    return JSON.stringify(Array.from({length:3},(_,i)=>({n:i+1,platform:i%2?'Facebook':'Instagram',format:['portrait','portrait','story'][i],date:`2026-10-${12+i*4}`,pillar:['Origem','Torra','Comunidade'][i],...P[i]})))}
  if(p.includes('Set the visual direction')){const L=libCodes(p);const ref1=L['ref-poster.jpg'],ref2=L['ref-arch.png'];return JSON.stringify({bigIdea:'Das colinas de Gurué à sua chávena: a origem como selo de orgulho.',concept:'Warm roast-brown and cream fields carry big condensed type, like a stamped coffee sack.',fromReferences:[ref1&&{code:ref1,take:'Heavy condensed capitals set huge, one round shape as a counterweight.'},ref2&&{code:ref2,take:'Photo framed in a tall arch on cream, serif headline underneath.'}].filter(Boolean),palette:[{hex:'#2B1A12',role:'background, text on cream'},{hex:'#F3E6D3',role:'background, text on brown'},{hex:'#C8742E',role:'accent'},{hex:'#3E5B3A',role:'support'}],typography:{display:{family:'Anton',weight:400,case:'upper'},text:{family:'DM Sans',weight:500},accent:{family:'Fraunces',weight:900}},photoTreatment:'Warm, darkened at the base.',graphicDevices:['round origin stamp','tall arch frame','fine cream inset frame'],layoutSystem:'Full-bleed photo, arch on cream, pure graphic.',logoRule:'Bottom right; white on dark, original on light.',posts:[{n:1,idea:'Origin as a stamp',layout:'full-bleed photo',images:[L['farm-gurue.jpg']].filter(Boolean),needsNewImage:false,imagePrompt:''},{n:2,idea:'Craft',layout:'arch',images:[L['barista-cup.jpg']||L['image1.jpeg']].filter(Boolean),needsNewImage:false,imagePrompt:''},{n:3,idea:'Saturday table',layout:'illustration',images:[],needsNewImage:true,imagePrompt:'Top view of three cups of black coffee on a wooden table, warm Saturday morning light, Maputo café, space at the top for text, photographic, no words'}]})}
  if(p.includes('checking your own post')){const m=/YOUR DESIGN\n([\s\S]*?<\/spec>)/.exec(p);return m?m[1]:'oops'}
  if(p.includes('could not render this design')){return d3()}
  if(/Design post (\d+)/.test(p)){const n=+/Design post (\d+)/.exec(p)[1];const imgs=(/Images planned for this post: ([^\n]*)/.exec(p)||[])[1]||'';const code=(imgs.match(/img-[0-9a-z]{8}/)||[])[0];if(p.includes('BROKEN-TEST')) return '<concept>x</concept><background><svg><rect></background><spec>{}</spec>';return n===1?d1(code):n===2?d2(code):d3()}
  if(p.includes('Brand QA lead')){return JSON.stringify({overall:'Bom conjunto, coerente. Dois pontos a confirmar com o cliente.',posts:[{n:1,score:5,issues:[],fix:null},{n:2,score:3,issues:['[PT] "Servido à quarta" promete um prazo que o brief não confirma.','[Design] O CTA está próximo do logótipo.'],fix:{pt:{headline:'Torrado à terça-feira'},en:{headline:'Roasted on Tuesdays'}}},{n:3,score:4,issues:['[PT] Confirmar se a prova é gratuita.'],fix:null}]})}
  if(p.includes('asked for changes to one post')){return JSON.stringify({pt:{headline:'Torra fresca, todas as semanas'},en:{headline:'Fresh roast, every week'}})}
  return '{}';
}
const PNG1=fs.readFileSync(path.join(__dirname,'assets','farm-gurue.jpg')).toString('base64');
http.createServer(async(req,res)=>{
  const u=new URL(req.url,'http://x');
  if(u.pathname==='/'){const html=fs.readFileSync(PAGE,'utf8');res.writeHead(200,{'content-type':'text/html; charset=utf-8'});return res.end(`<!doctype html><html><head><meta charset=utf8><meta name=viewport content="width=device-width,initial-scale=1,viewport-fit=cover">${RESET}</head><body>${html}</body></html>`)}
  if(u.pathname==='/_state'){if(req.method==='POST'){state=JSON.parse((await body(req)).toString());fs.writeFileSync(path.join(OUT,'state.json'),JSON.stringify(state,null,1));return res.end('ok')}res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify(state))}
  if(u.pathname==='/_upload'){const b=await body(req);const id=crypto.randomBytes(16).toString('hex');blobs.set(id,{type:u.searchParams.get('type'),b});res.writeHead(200,{'content-type':'application/json'});return res.end(JSON.stringify({id}))}
  if(u.pathname.startsWith('/_blob/')){const x=blobs.get(u.pathname.slice(7));if(!x){res.writeHead(404);return res.end()}res.writeHead(200,{'content-type':x.type});return res.end(x.b)}
  if(u.pathname==='/_download'){const b=await body(req);fs.writeFileSync(path.join(OUT,u.searchParams.get('name')),b);return res.end('ok')}
  if(u.pathname==='/_sampleimg'){const b=await body(req);fs.writeFileSync(path.join(OUT,'sample',`call${u.searchParams.get('call')}-${u.searchParams.get('k')}.bin`),b);return res.end('ok')}
  if(u.pathname==='/_sample'){const {input,nImages,tier}=JSON.parse((await body(req)).toString());const p=typeof input==='string'?input:input.map(t=>t.content).join('\n');const call=u.searchParams.get('call');fs.writeFileSync(path.join(OUT,'sample',`call${call}-prompt.txt`),`tier=${tier} images=${nImages}\n\n`+p);const r=respond(p);log.push({call,kind:p.slice(0,60),nImages,tier});fs.writeFileSync(path.join(OUT,'sample',`call${call}-reply.txt`),r);return res.end(r)}
  if(u.pathname==='/_mcp'){const {tool,input}=JSON.parse((await body(req)).toString());fs.appendFileSync(path.join(OUT,'mcp.log'),JSON.stringify({tool,input})+'\n');res.writeHead(200,{'content-type':'application/json'});
    if(tool==='generate-image') return res.end(JSON.stringify({content:[{type:'text',text:'{"jobId":"job_abc123"}'}],payload:{jobId:'job_abc123'}}));
    if(tool==='get-generate-image-job'&&MODE.canva==='links') return res.end(JSON.stringify({content:[{type:'text',text:'Status: SUCCESS. Open generated image: https://www.canva.com/design/DAGtest123/view'}],payload:{status:'SUCCESS',result:{url:'https://www.canva.com/design/DAGtest123/view'}}}));
    if(tool==='get-generate-image-job'&&MODE.canva==='fail') return res.end(JSON.stringify({content:[{type:'text',text:'failed'}],payload:{status:'FAILURE',failureMessage:'Prompt was blocked'}}));
    if(tool==='get-generate-image-job') return res.end(JSON.stringify({content:[{type:'text',text:'Status SUCCESS. Open generated image: https://www.canva.com/design/xyz'},{type:'image',data:PNG1,mimeType:'image/jpeg'}],payload:{status:'SUCCESS'}}));
    return res.end('{}')}
  if(u.pathname==='/_mode'){MODE={...MODE,...JSON.parse((await body(req)).toString())};return res.end(JSON.stringify(MODE))}
  if(u.pathname==='/_log'){return res.end(JSON.stringify(log))}
  res.writeHead(404);res.end();
}).listen(+process.env.PORT||8765,()=>console.log('listening'));
